teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - SeanBohan
      - thelinuxfoundation
  - name: accountable-impact-commons-maintainers
    maintainers:
      - AlexIvanHoward
      - AlfonsoGovela
    members:
      - christiaanpauw
      - JSPApril
      - liamswan
repositories:
  - name: governance
    teams:
      accountable-impact-commons-maintainers: write
      lf-staff: maintain
    visibility: public
  - name: aiao
    teams:
      accountable-impact-commons-maintainers: maintain
    visibility: public
  - name: claimont
    teams:
      accountable-impact-commons-maintainers: maintain
    visibility: public
  - name: impactont
    teams:
      accountable-impact-commons-maintainers: maintain
    visibility: public
  - name: infocomm
    teams:
      accountable-impact-commons-maintainers: maintain
    visibility: public
