teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
  - name: semantic-frameworks-maintainers
    maintainers:
      - AlfonsoGovela
      - AlexIvanHoward
    members:
      - christiaanpauw
      - liamswan
      - JSPApril
repositories:
  - name: governance
    teams:
      lf-staff: maintain
      semantic-frameworks-maintainers: write
    visibility: public
  - name: aiao
    teams:
      semantic-frameworks-maintainers: maintain
    visibility: public
  - name: claimont
    teams:
      semantic-frameworks-maintainers: maintain
    visibility: public
  - name: impactont
    teams:
      semantic-frameworks-maintainers: maintain
    visibility: public
  - name: infocomm
    teams:
      semantic-frameworks-maintainers: maintain
    visibility: public
